apiVersion: v1
kind: Pod
metadata:
  name: leopard-crossing-pod
  labels:
    app: leopard-crossing
spec:
  containers:
    - name: leopard-crossing-api
      image: quay.io/rbrhssa/leopard_pontdesarts:latest
      ports:
        - containerPort: 8000
          hostPort: 8000
      envFrom:
        - configMapRef:
            name: leopard-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: leopard-config
data:
  # LlamaStack Configuration
  LLAMASTACK_BASE_URL: "https://lss-lss.apps.cluster-nngf2.dynamic.redhatworkshops.io/v1"
  LLAMASTACK_MODEL: "remote-llm/llama-4-scout-17b-16e-w4a16"
  LLAMASTACK_API_KEY: ""
  
  # Application Configuration
  LOG_LEVEL: "INFO"
  CONFIG_DIR: "/app/configs"
